Algoritmo "Media"

// Autor(a): João Pedro Barauna
// Data: 03/08/2026

Var
  // Seção de Declarações das variáveis
  nota1, nota2, media : real

Inicio
  // Seção de Comandos
  escreval("informe a priemiro nota")
  leia(nota1)
  escreval("A priemira nota é ", nota1)

  escreval ("Informme a segunda nota")
  leia(nota2)
  escreval("A segunda nota é ",nota2)


  media <- (nota1 + nota2) / 2

  escreval ("A média das notas é ",media)

fimalgoritmo