Algoritmo "Dobro_Triplo_Número"

// Autor(a): João Pedro Barauna
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
numero, dobro, triplo : inteiro

Inicio
// Seção de Comandos
escreval("inform um numero: ")
leia(numero)

dobro <- numero * 2
triplo <- numero * 3

escreval ("O numero informado foi ",numero)
escreval ("O dobro de ",numero," é ", dobro)
escreval ("O triplo de ",numero," é ", triplo)

fimalgoritmo