Algoritmo "Aula3_Ex12_Contagem_Regressiva"
// Autor: João Pedro Baraúna
// Aula: 3
// Exercício: 12
// Resumo: Faz uma contagem regressiva de 10 a 1.

Var
  i : inteiro

Inicio
  // Inicia o contador no 10, e vai diminuindo 1 (passo -1) até chegar no 1
  para i de 10 ate 1 passo -1 faca
    escreval(i) // Mostra o número na tela
  fimpara

  // Ao terminar o laço de repetição, exibe a mensagem comemorativa
  escreval("Feliz Ano novo!")
fimalgoritmo