Algoritmo "AreaTriangulo"

// Autor(a): João Pedro Barauna
// Data: 03/08/2026

Var
// Seção de Declarações das variáveis
base, altura, area: real

Inicio
// Seção de Comandos
escreval ("informa o valor da base do triangulo: ")
leia(base)
escreval("A base do triangulo é  ", base)


escreval ("informa o valor da altura  do triangulo: ")
leia(altura)
escreval ("A altura do triangulo é  ", altura)

area <- (base * altura) / 2

escreval ("A área  do triangulo é  ", area)



fimalgoritmo